### ISSUE TITLE
[Android] Crashes when using cordova.plugins.barcodeScanner.encode()

### ISSUE THREAD

**Issue by roblav96** [phonegap/phonegap-plugin-barcodescanner#174]
This simple code:
```
		cordova.plugins.barcodeScanner.encode( cordova.plugins.barcodeScanner.Encode.TEXT_TYPE, "http://www.nytimes.com", function ( success ) {
			console.log( 'success >', success )
		}, function ( err ) {
			console.error( err )
		} )
```

Crashes Android :(

```
I/ActivityManager(  757): START u0 {act=com.phonegap.plugins.barcodescanner.ENCODE pkg=com.tech.testapp cmp=com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity (has extras)} from uid 10403 on display 0
V/WindowManager(  757): addAppToken: AppWindowToken{1b7804ff token=Token{2daeb41e ActivityRecord{2f6a4059 u0 com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity t1914}}} to stack=1 task=1914 at 1
I/TSLocationManager( 2742): - onPause
V/WindowManager(  757): Adding window Window{140a7fb8 u0 com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity} at 8 of 14 (after Window{3b1c5110 u0 com.tech.testapp/com.tech.testapp.MainActivity})
I/chromium( 2742): [INFO:CONSOLE(8464)] "_$socket.unload", source: http://192.168.1.125:8100/build.js (8464)
D/AndroidRuntime( 2742): Shutting down VM
E/AndroidRuntime( 2742): FATAL EXCEPTION: main
E/AndroidRuntime( 2742): Process: com.tech.testapp, PID: 2742
E/AndroidRuntime( 2742): java.lang.reflect.UndeclaredThrowableException
E/AndroidRuntime( 2742): 	at $Proxy1.onCreatePanelMenu(Unknown Source)
E/AndroidRuntime( 2742): 	at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:600)
E/AndroidRuntime( 2742): 	at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:972)
E/AndroidRuntime( 2742): 	at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:309)
E/AndroidRuntime( 2742): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 2742): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2742): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2742): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 2742): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2742): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2742): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 2742): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 2742): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2742): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2742): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2742): 	at org.chromium.base.ApplicationStatusManager$WindowCallbackProxy.invoke(ApplicationStatusManager.java:62)
E/AndroidRuntime( 2742): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/AndroidRuntime( 2742): 	... 12 more
E/AndroidRuntime( 2742): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setTitle(int)' on a null object reference
E/AndroidRuntime( 2742): 	at com.google.zxing.client.android.encode.EncodeActivity.onCreateOptionsMenu(EncodeActivity.java:88)
E/AndroidRuntime( 2742): 	at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
E/AndroidRuntime( 2742): 	... 16 more
W/ActivityManager(  757):   Force finishing activity 1 com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity
W/ActivityManager(  757):   Force finishing activity 2 com.tech.testapp/.MainActivity
I/OpenGLRenderer(  757): Initialized EGL, version 1.4
W/ActivityManager(  757): Activity pause timeout for ActivityRecord{2f6a4059 u0 com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity t1914 f}
I/Timeline( 1405): Timeline: Activity_idle id: android.os.BinderProxy@1e636e2e time:220722892
I/Timeline(  757): Timeline: Activity_windows_visible id: ActivityRecord{2c1f598a u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t1835} time:220723041
W/ResourceType( 1073): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1073): Failure retrieving resources for com.tech.testapp: Resource ID #0x0
I/Process ( 2742): Sending signal. PID: 2742 SIG: 9
D/audio_hw_primary(  310): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
D/audio_hw_primary(  310): start_output_stream: enter: stream(0xb58804c0)usecase(1: low-latency-playback) devices(0x2)
D/audio_hw_primary(  310): start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
D/audio_hw_primary(  310): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
W/msm8974_platform(  310): Codec backend bitwidth 16, samplerate 48000
D/hardware_info(  310): hw_info_append_hw_type : device_name = speaker
I/msm8974_platform(  310): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
I/tfa9887 (  310): tfa9887_power: Set amplifier power to 1
D/audio_hw_primary(  310): select_devices: done
I/WindowState(  757): WIN DEATH: Window{140a7fb8 u0 com.tech.testapp/com.google.zxing.client.android.encode.EncodeActivity}
I/WindowState(  757): WIN DEATH: Window{3b1c5110 u0 com.tech.testapp/com.tech.testapp.MainActivity}
```

**Comment by g-viana** [comment]
I had the same issue, but I found this on the old repository for this plugin:
https://github.com/wildabeast/BarcodeScanner/issues/306

I changed the XML and now it works, don't know why they removed it though

**Comment by hervethouzard** [comment]
Hello,

Same thing for me, Cordova v6.1.0, Android 5.1 and ionic v1.7.14

**Comment by roblav96** [comment]
how do you fix it? what to change in the xml?

**Comment by hervethouzard** [comment]
Follow the given link and copy/paste its content in your local version:
https://github.com/wildabeast/BarcodeScanner/issues/306

**Comment by roblav96** [comment]
@hervethouzard Ah, thank you!!! I'll try this out.

**Comment by ihadeed** [comment]
Hey there

I'm just here to follow up with this issue.

Has it been resolved? Is it safe to use the encode/decode functions and not have the application crash?

Thank you.
