### ISSUE TITLE
cordova build android fails using this plugin

### ISSUE THREAD

**Issue by remauth** [phonegap/phonegap-plugin-barcodescanner#282]
Hello,
I use cordova 6.2.0. The build works with ios and fails with android.
The failure appears only when this plugin is used. See below the messages:

:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

BUILD FAILED

Total time: 7.75 secs
Error: Error code 1 for command: /Users/project/_cordova/remauth/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/project/_cordova/remauth/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

Thank you for your help

**Comment by remauth** [comment]
Solved. See http://stackoverflow.com/questions/26342444/multiple-dex-files-define-landroid-support-annotation-animres

Just delete the file `/platforms/android/libs/android-support-v4.jar` to make it work
