### ISSUE TITLE
please ,need help,when i invoke scan method,the app forced close and exception like this,anyone have any idea?

### ISSUE THREAD

**Issue by MrScript** [phonegap/phonegap-plugin-barcodescanner#293]
07-26 17:01:30.074  32309-32309/com.pengqi.ios.union E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.pengqi.ios.union, PID: 32309
    java.lang.NoClassDefFoundError: Failed resolution of: Lbarcodescanner/xservices/nl/barcodescanner/R$layout;
            at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:142)
            at android.app.Activity.performCreate(Activity.java:6107)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
            at android.app.ActivityThread.access$800(ActivityThread.java:179)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
            at android.os.Handler.dispatchMessage(Handler.java:111)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5803)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "barcodescanner.xservices.nl.barcodescanner.R$layout" on path: DexPathList[[zip file "/data/app/com.pengqi.ios.union-2/base.apk"],nativeLibraryDirectories=[/data/app/com.pengqi.ios.union-2/lib/arm64, /vendor/lib64, /system/lib64]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:142)
            at android.app.Activity.performCreate(Activity.java:6107)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
            at android.app.ActivityThread.access$800(ActivityThread.java:179)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
            at android.os.Handler.dispatchMessage(Handler.java:111)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5803)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
    Suppressed: java.lang.ClassNotFoundException: barcodescanner.xservices.nl.barcodescanner.R$layout
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.
