### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by MrScript** [phonegap/phonegap-plugin-barcodescanner#421]
when i invoke the scan method,the app force close and show class not found exception,have anyone know what's the problem? it seems like missing something? 

Caused by: java.lang.ClassNotFoundException: Didn't find class "barcodescanner.xservices.nl.barcodescanner.R$layout" on path: DexPathList[[zip file "/data/app/com.pq.apk.anjianju-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pq.apk.anjianju-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:150)
            at android.app.Activity.performCreate(Activity.java:6127)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
            at android.app.ActivityThread.access$900(ActivityThread.java:187)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
            at android.os.Handler.dispatchMessage(Handler.java:111)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5869)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by jcesarmobile** [comment]
How are you running the app?

**Comment by MrScript** [comment]
@jcesarmobile what's your mean?

**Comment by jcesarmobile** [comment]
how are you running the app in your device?

Are you using Cordova CLI? (`cordova run android --device`)
and IDE?
are you using an app like phonegap developer app or ionic view?

**Comment by MrScript** [comment]
@jcesarmobile  i use IntelliJ IDEA 15.0.3 to develpoer

**Comment by MrScript** [comment]
@jcesarmobile thx,i will try
