### ISSUE TITLE
Android cancel scan bug

### ISSUE THREAD

**Issue by houssem2101** [phonegap/phonegap-plugin-barcodescanner#476]
Cancel Scan with the hardware back button causes the app exit

05-26 14:20:10.496 1394-1403/io.ionic.starter E/System: Uncaught exception thrown by finalizer
05-26 14:20:10.497 1394-1403/io.ionic.starter E/System: java.lang.IllegalStateException: Binder has been finalized!
                                                            at android.os.BinderProxy.transactNative(Native Method)
                                                            at android.os.BinderProxy.transact(Binder.java:615)
                                                            at com.android.internal.app.IAppOpsService$Stub$Proxy.stopWatchingMode(IAppOpsService.java:435)
                                                            at android.media.PlayerBase.baseRelease(PlayerBase.java:136)
                                                            at android.media.MediaPlayer.finalize(MediaPlayer.java:2810)
                                                            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                            at java.lang.Thread.run(Thread.java:761)

**Comment by macdonst** [comment]
@houssem2101 Can we get some more information on this bug?

**Comment by justinhenricks** [comment]
Cancel on Android is throwing me out of the app.

**Comment by justinhenricks** [comment]
I have found that when I had my orientation explicitly set (landscape eg.) that I put the phone in portrait and hit the back button my app was hard closing out. I removed the orientation config and seems to be working fine now.

**Comment by macdonst** [comment]
Closing, inactivity. Please comment/re-open if you have more details.

**Comment by Fever905** [comment]
This is still occurring with current version.  You launch the scanner and click the back button on Android 8 and the app exits and closes.   I'm not sure how to get those debug logs as in the first post. I'm on an Nexus 6P using Phonegap/Cordova

**Comment by fappels** [comment]
Maybe your app is also listening to the backbutton event, check issue #355

**Comment by Jacob-McKay** [comment]
Back button in my app cancels scan in all android versions we've tested except 8 which closes the app.  I will follow up on @fappels suggestion but I can say this is new behavior that only effects android 8 phones running our app.
