### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.google.zxing.client.android.pref.BSPlusPreference

### ISSUE THREAD

**Issue by oriharel** [phonegap/phonegap-plugin-barcodescanner#491]
### Expected Behaviour
App to work

### Actual Behaviour
App crashes on Java exception

### Reproduce Scenario (including but not limited to)
Just invoke cordova.plugins.barcodeScanner.scan() method from JavaScript

#### Steps to Reproduce
Just invoke cordova.plugins.barcodeScanner.scan() method from JavaScript

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.1

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Emulator

#### Cordova CLI version and cordova platform version

    cordova --version => 7.0.1
    cordova platforms 

  Installed platforms:
  android 5.0.0
  ios 4.1.1

#### Plugin version

phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

#### Sample Code that illustrates the problem

cordova.plugins.barcodeScanner.scan(
        function (result) {
            alert("We got a barcode\n" +
                "Result: " + result.text + "\n" +
                "Format: " + result.format + "\n" +
                "Cancelled: " + result.cancelled);
        },
        function (error) {
            alert("Scanning failed: " + error);
        },
        {
            preferFrontCamera : true, // iOS and Android
            showFlipCameraButton : true, // iOS and Android
            showTorchButton : true, // iOS and Android
            torchOn: true, // Android, launch with the torch switched on (if available)
            prompt : "Place a barcode inside the scan area", // Android
            resultDisplayDuration: 500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500
            formats : "QR_CODE,PDF_417", // default: all but PDF_417 and RSS_EXPANDED
            orientation : "landscape", // Android only (portrait|landscape), default unset so it rotates with the device
            disableAnimations : true, // iOS
            disableSuccessBeep: false // iOS
        }
    );

#### Logs taken while reproducing problem

06-25 15:32:28.147 18203-18290/org.capriza.local.store D/FabricPlugin: FabricPlugin called with options: ["LOG - 2017-06-25T12:32:28.146Z: Card - slide onclick"]
06-25 15:32:28.147 18203-18203/org.capriza.local.store I/chromium: [INFO:CONSOLE(53)] "LOG - 2017-06-25T12:32:28.146Z: Card - slide onclick", source: webpack:///./javascripts/services/logger.js? (53)
06-25 15:32:28.152 18203-18203/org.capriza.local.store I/chromium: [INFO:CONSOLE(53)] "INFO - 2017-06-25T12:32:28.152Z: zapp runner - running zapp with url https://zappdev.capriza.com/cQWdEhEfgoFYtXfG1QWqDg and data [object Object], rtTrustedCerts: undefined, rtTrustedKeys: undefined, ssoCookies: true", source: webpack:///./javascripts/services/logger.js? (53)
06-25 15:32:28.153 18203-18290/org.capriza.local.store D/FabricPlugin: FabricPlugin called with options: ["INFO - 2017-06-25T12:32:28.152Z: zapp runner - running zapp with url https:\/\/zappdev.capriza.com\/cQWdEhEfgoFYtXfG1QWqDg and data [object Object], rtTrustedCerts: undefined, rtTrustedKeys: undefined, ssoCookies: true"]
06-25 15:32:28.168 18203-18203/org.capriza.local.store D/CaprizaActivity: onPause called
06-25 15:32:28.178 18203-18290/org.capriza.local.store D/FabricPlugin: FabricPlugin called with options: ["LOG - 2017-06-25T12:32:28.176Z: app paused"]
06-25 15:32:28.183 18203-18290/org.capriza.local.store D/FabricPlugin: FabricPlugin called with options: ["LOG - 2017-06-25T12:32:28.181Z: Analytics Service - Track event: category: App State, action: Pause, label: undefined, value: undefined"]
06-25 15:32:28.214 18203-18203/org.capriza.local.store D/MediaPlayer: setSubtitleAnchor in MediaPlayer
06-25 15:32:28.222 18203-18203/org.capriza.local.store D/AndroidRuntime: Shutting down VM
06-25 15:32:28.318 18203-18203/org.capriza.local.store E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.capriza.local.store, PID: 18203
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{org.capriza.local.store/com.google.zxing.client.android.CaptureActivity}: android.view.InflateException: Binary XML file line #98: Error inflating class com.google.zxing.client.android.pref.BSPlusPreference
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                          Caused by: android.view.InflateException: Binary XML file line #98: Error inflating class com.google.zxing.client.android.pref.BSPlusPreference
                                                                             at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:443)
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:483)
                                                                             at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:327)
                                                                             at android.preference.GenericInflater.inflate(GenericInflater.java:264)
                                                                             at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:609)
                                                                             at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:568)
                                                                             at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:157)
                                                                             at android.app.Activity.performCreate(Activity.java:6679)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
06-25 15:32:28.318 18203-18203/org.capriza.local.store E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.zxing.client.android.pref.BSPlusPreference" on path: DexPathList[[zip file "/data/app/org.capriza.local.store-2/base.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_dependencies_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_0_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_1_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_2_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_3_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_4_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_5_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_6_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_7_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_8_apk.apk", zip file "/data/app/org.capriza.local.store-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.capriza.local.store-2/lib/x86, /system/fake-libs, /data/app/org.capriza.local.store-2/base.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_dependencies_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_0_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_1_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_2_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_3_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_4_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_5_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_6_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_7_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_8_apk.apk!/lib/x86, /data/app/org.capriza.local.store-2/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                             at android.preference.GenericInflater.createItem(GenericInflater.java:376)
                                                                             at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432)
                                                                             	... 20 more
06-25 15:32:29.567 18203-18243/org.capriza.local.store I/CrashlyticsCore: Crashlytics report upload complete: 594FAD510045-0001-471B-136DB751E7B9.cls

**Comment by macdonst** [comment]
@oriharel I can't reproduce this. Can you upgrade to cordova-android 6.x and retest?

**Comment by maverickmishra** [comment]
Closing this issue due to inactivity. Please feel free to re-open if the issue is still not resolved.
