### ISSUE TITLE
phoengap build + v 0.7.2

### ISSUE THREAD

**Issue by vousys** [phonegap/phonegap-plugin-barcodescanner#537]
Hi Simon, this problem is happening since last days. The version 0.7.2 is having any issue in android (not in ios) and we can't compile the app via phonegap build
this is the error that shows:

```
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
[Fatal Error] :16:352: The value of the attribute "prefix="xmlns",localpart="android",rawname="xmlns:android"" is invalid. Prefixed namespace bindings may not be empty.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'project'.
> Exception while parsing the supplied manifest file /project/AndroidManifest.xml
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1.501 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
[Fatal Error] :16:352: The value of the attribute "prefix="xmlns",localpart="android",rawname="xmlns:android"" is invalid. Prefixed namespace bindings may not be empty.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'project'.
> Exception while parsing the supplied manifest file /project/AndroidManifest.xml
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```
These guys are having the same issue as me:
https://forums.adobe.com/thread/2374568
the only way to compile is downgrading to v 0.7.1 
 
Thanks.

**Comment by macdonst** [comment]
@vousys [cordova-plugin-barcodescanner](https://github.com/hypery2k/cordova-barcodescanner-plugin) is a completely different plugin than this one. You'd have to raise the issue with that projects maintainer.

**Comment by vousys** [comment]
Excuse me Simon, my mistake.
