### ISSUE TITLE
Failed to install 'phonegap-plugin-barcodescanner': Error: ENOENT: no such file or directory, open '\platforms\android\AndroidManifest.xml'

### ISSUE THREAD

**Issue by tgsouto** [phonegap/phonegap-plugin-barcodescanner#610]
### Expected Behaviour

Successfully add platform

### Actual Behaviour

Error adding platform
Failed to install 'phonegap-plugin-barcodescanner': Error: ENOENT: no such file or directory, open '\platforms\android\AndroidManifest.xml'

### Reproduce Scenario (including but not limited to)

    cordova plugin add phonegap-plugin-barcodescanner
    cordova platform add android

#### Cordova CLI version and cordova platform version

    cordova --version: 8.0.0
    cordova platforms:
    Installed platforms:
      android 7.0.0
    Available platforms:
      browser ~5.0.1
      ios ~4.5.4
      osx ~4.0.1
     windows ~5.0.0
     www ^3.12.0

#### Plugin version

    phonegap-plugin-barcodescanner 7.0.2 "BarcodeScanner"

#### Logs taken while reproducing problem
    Failed to install 'phonegap-plugin-barcodescanner': Error: ENOENT: no such file or directory, open '\platforms\android\AndroidManifest.xml'
        at Error (native)
        at Object.fs.openSync (fs.js:641:18)
        at Object.fs.readFileSync (fs.js:509:33)
        at Object.parseElementtreeSync (\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
        at new AndroidManifest (\platforms\android\cordova\lib\AndroidManifest.js:29:20)
        at AndroidProject.getPackageName (\platforms\android\cordova\lib\AndroidProject.js:99:12)
        at Api.addPlugin (\platforms\android\cordova\Api.js:223:57)
        at handleInstall (\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
        at \AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
        at _fulfilled (\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)

**Comment by tgsouto** [comment]
I made a new test and the error only happens when there are other plugins, for now I will close this issue

**Comment by jcesarmobile** [comment]
Yeah, this happens when some plugin is not updated correctly to cordova-android 7. Probably by using source-file tags for images instead of resource-files
