### ISSUE TITLE
this make "Telerik-Verified-Plugins/ImagePicker" not running well

### ISSUE THREAD

**Issue by Moobusy** [phonegap/phonegap-plugin-barcodescanner#635]
Installed https://github.com/Telerik-Verified-Plugins/ImagePicker and this；
this run well, but imagepicker is error.

when uninstall this, imagepicker is ok

#### simple code
this.imagePicker.getPictures(options).then(images => {
            console.log(images)
        }, error => {
            console.log('Error: ' + error);
        });

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.0
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Xiaomi；Ivvi；
#### Cordova CLI version and cordova platform version

    cordova --version：8.0.0
    cordova platforms：
Installed platforms:
  android 6.3.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

#### Plugin version
    7.1.0

#### Logs taken while reproducing problem
io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: io.ionic.starter, PID: 21032
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/graphics/drawable/DrawableWrapper;
                                                                      at android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:147)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:257)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:207)
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                      at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:184)
                                                                      at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:91)
                                                                      at android.support.v7.widget.Toolbar.getWrapper(Toolbar.java:1780)
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.getDecorToolbar(ActionBarOverlayLayout.java:538)
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.pullChildren(ActionBarOverlayLayout.java:530)
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.setWindowCallback(ActionBarOverlayLayout.java:606)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:399)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                      at com.synconset.MultiImageChooserActivity.onCreate(MultiImageChooserActivity.java:130)
                                                                      at android.app.Activity.performCreate(Activity.java:6858)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:163)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6337)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.graphics.drawable.DrawableWrapper" on path: DexPathList[[zip file "/data/app/io.ionic.starter-2/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                      at android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:147) 
                                                                      at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:257) 
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:207) 
                                                                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192) 
                                                                      at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:184) 
                                                                      at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:91) 
                                                                      at android.support.v7.widget.Toolbar.getWrapper(Toolbar.java:1780) 
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.getDecorToolbar(ActionBarOverlayLayout.java:538) 
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.pullChildren(ActionBarOverlayLayout.java:530) 
                                                                      at android.support.v7.widget.ActionBarOverlayLayout.setWindowCallback(ActionBarOverlayLayout.java:606) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:399) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277) 
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                      at com.synconset.MultiImageChooserActivity.onCreate(MultiImageChooserActivity.java:130) 
                                                                      at android.app.Activity.performCreate(Activity.java:6858) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:163) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6337) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by digows** [comment]
Still happening

**Comment by jcesarmobile** [comment]
The problem is the image picker plugin
