### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by sabiridwan** [phonegap/phonegap-plugin-barcodescanner#638]
### Reproduce Scenario (including but not limited to)
- open scanner
- scan code
- app crash after scanning

#### Steps to Reproduce
- open scanner
- scan code
- app crash after scanning

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 7.1.2

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Redmi 4X

#### Cordova CLI version and cordova platform version

    cordova --version 8.0.0
    cordova platforms android 7.1.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-barcodescanner

**Comment by jcesarmobile** [comment]
Can you provide the code you are using?

Also the stack trace might be helpful (check it on logcat)

**Comment by bhumin3i** [comment]
@jcesarmobile  same problem 

```
  var option = {
            showTorchButton: true,
            resultDisplayDuration: 0
          }
          this.barcodeScanner.scan(option).then(
            barcodeData => {});
```

**Comment by jcesarmobile** [comment]
@bhumin3i did you set the Camera usage description in your config.xml as explained in the README?

**Comment by bhumin3i** [comment]
@jcesarmobile  I'm adding privacy camera user in info.plist but how to add using config.xml

I'm using 
 <platform name="ios">
        <edit-config file="*-Info.plist" mode="merge" overwrite="true" target="NSPhotoLibraryUsageDescription">
            <string>RTI would like to use your Camera</string>
        </edit-config>
        <edit-config file="*-Info.plist" mode="merge" overwrite="true" target="NSCameraUsageDescription">
            <string>RTI would like to use your Camera</string>
        </edit-config>
    </platform>
but it does not work..

**Comment by jcesarmobile** [comment]
So it's not the same issue, this issue is about Android

**Comment by sabiridwan** [comment]
hi @jcesarmobile thanks for your help.

The app automatically close after scanning i can't see any errors. please if you have any idea on seeing error in such case help me out

here is my code 
==========================
 scan(): Promise<any> {
        return this.barcodeScanner.scan().then(barcodeData => {
            console.log('Barcode data', barcodeData);
            return Promise.resolve(barcodeData);
        }).catch(err => {
            console.log('Error', err);
            return Promise.reject(err);
        });
    }

**Comment by jarekskuder** [comment]
Same here, only my app crashes when i call the scanner

**Comment by jcesarmobile** [comment]
@jarekskuder instead of repeating your comment on multiple issues, you could provide more information about the crash to help us track down the problem

**Comment by jcesarmobile** [comment]
If it crash, logcat should show the error.
You can also provide the code you are using. Cordova version, plugin version, cordova-android version, etc.

**Comment by jarekskuder** [comment]
Cordova version: 7.0.1
Plugin version: 6.0.1
android-platform: 6.3.0

Code:
 ```
var scanner_config = [i18n.translate('pos.scan_prompt')];
cordova.plugins.barcodeScanner.scan(
                    function (result) {
                            console.log(result);
                    },
                    function (error) {
                        app.stopSpinner();
                    },
                    scanner_config
                );
```

Logcat: 

04-11 13:04:28.379  7852  8040 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
04-11 13:04:28.379  7852  8040 E AndroidRuntime: Process: com.worapay.worapay, PID: 7852
04-11 13:04:28.379  7852  8040 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.zxing.client.android.SCAN cat=[android.intent.category.DEFAULT] pkg=com.worapay.worapay launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4403)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4362)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:66)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at com.phonegap.plugins.barcodescanner.BarcodeScanner$1.run(BarcodeScanner.java:191)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-11 13:04:28.379  7852  8040 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)

**Comment by icvitkovac** [comment]
This is still an issue; I'm having the same problems as @jarekskuder described even with latest version of the plugin. 

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.1.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.11.1
    npm   : 5.6.0
    OS    : macOS High Sierra
    Xcode : Xcode 9.4.1 Build version 9F2000`

**Comment by jcesarmobile** [comment]
Please, report a new issue, this one is closed and doesn't look like the original issue.
