### ISSUE TITLE
Scanner doest work if app is downloaded from Google Play store

### ISSUE THREAD

**Issue by terranmarine** [phonegap/phonegap-plugin-barcodescanner#793]
### Expected Behaviour
Scanner should work in both prod and dev env.
### Actual Behaviour
Works in dev and local env, but not on prod.
#### Steps to Reproduce
Deploy ur app to Google play store and try to scan a code. App Crashes after permission dialog is accepted.
#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0 
Android 9.0.0 
#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Tested on - Sony Experia X Compact
Samsung Galaxy Note 8
#### Cordova CLI version and cordova platform version
    Cordova version
    `8.1.2 (cordova-lib@8.1.1)`
    Cordova platforms
`Installed platforms:
  android 8.0.0
  ios 5.0.0
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0`

#### Plugin version

`phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"`

#### Logs taken while reproducing problem

Plugin works okay if I deploy locally on device (`ionic cordova run android --device`) or emulator. (works with `--prod` flag as well)
But if the download the deploy from Google play store, the plugin crashes the app after permissions dialog is accepted.

A Colleague  managed to find a stack trace that represents the issue:

`2019-06-07 14:27:02.892 16572-16629/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
  Process: appName, PID: 16572
  android.content.ActivityNotFoundException: Unable to find explicit activity class {appName2/com.google.zxing.client.android.CaptureActivity}; have you declared this activity in your AndroidManifest.xml?
      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1978)
      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1637)
      at android.app.Activity.startActivityForResult(Activity.java:4733)
      at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:343)
      at android.app.Activity.startActivityForResult(Activity.java:4673)
      at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:68)
      at com.phonegap.plugins.barcodescanner.BarcodeScanner$1.run(BarcodeScanner.java:204)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
      at java.lang.Thread.run(Thread.java:784)`

**Comment by terranmarine** [comment]
After a few days of fight we managed to get a working plugin on `prod`. 
Note: We are using Ionic Hub to build our `apk` and `ipa` files which probably caused the issue in the first place, not sure thought.
We generated the apk with working plugin locally using `codrova build --prod -release`, we also singed it locally using build.json.
Also, before building the working apk we removed  another plugin from our app - Telerik ImagePicker.
This might also be related.

Leaving this here in case someone else is having this problem.
Regards,
Alex.
